
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      # - rabbitmq-data:/var/lib/rabbitmq

  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "21239Admin"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

  invoicingconsumer:
    image: ${DOCKER_REGISTRY-}invoicingconsumer
    build:
      context: .
      dockerfile: InvoicingConsumer/Dockerfile
    restart: on-failure:10
    environment:
      EventStreamHostName: "rabbitmq"

  crmconsumer:
    image: ${DOCKER_REGISTRY-}crmconsumer
    build:
      context: .
      dockerfile: CRMConsumer/Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: on-failure:10
    environment:
      EventStreamHostName: "rabbitmq"

  loggingconsumer:
    image: ${DOCKER_REGISTRY-}loggingconsumer
    build:
      context: .
      dockerfile: LoggingConsumer/Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: on-failure:10
    environment:
      EventStreamHostName: "rabbitmq"
      ConnectionString: "Data Source=db;Initial Catalog=event_logger;User=sa;Password=21239Admin;Encrypt=False"

  warehouseconsumer:
    image: ${DOCKER_REGISTRY-}warehouseconsumer
    build:
      context: .
      dockerfile: WarehouseConsumer/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure:10
    environment:
      EventStreamHostName: "rabbitmq"

  shippingconsumer:
    image: ${DOCKER_REGISTRY-}shippingconsumer
    build:
      context: .
      dockerfile: ShippingConsumer/Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure:10
    environment:
      EventStreamHostName: "rabbitmq"
      
  eda-seq:
    image: datalust/seq:latest
    container_name: runtrackr.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
      
volumes:
  mssql-data:
  # rabbitmq-data:
