version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "21239Admin"
      ACCEPT_EULA: "Y"

  invoicingconsumer:
    image: ${DOCKER_REGISTRY-}invoicingconsumer
    build:
      context: .
      dockerfile: InvoicingConsumer/Dockerfile

  crmconsumer:
    image: ${DOCKER_REGISTRY-}crmconsumer
    build:
      context: .
      dockerfile: CRMConsumer/Dockerfile
    depends_on:
      - db

  loggingconsumer:
    image: ${DOCKER_REGISTRY-}loggingconsumer
    build:
      context: .
      dockerfile: LoggingConsumer/Dockerfile
    depends_on:
      - db

  warehouseconsumer:
    image: ${DOCKER_REGISTRY-}warehouseconsumer
    build:
      context: .
      dockerfile: WarehouseConsumer/Dockerfile
    depends_on:
      - db

  shippingconsumer:
    image: ${DOCKER_REGISTRY-}shippingconsumer
    build:
      context: .
      dockerfile: ShippingConsumer/Dockerfile
    depends_on:
      - db

  


